const (
	IN_JMP = PROG_PRIMITIVE(1)
	IN_READ = PROG_PRIMITIVE(2)
	IN_SLEEP = PROG_PRIMITIVE(3)
	IN_CALL = PROG_PRIMITIVE(4)
	IN_EXECUTE = PROG_PRIMITIVE(5)
	IN_RET = PROG_PRIMITIVE(6)
	IN_EVENT_WAITFOR = PROG_PRIMITIVE(7)
	IN_CATCH = PROG_PRIMITIVE(8)
	IN_CATCH_DETAILED = PROG_PRIMITIVE(9)
)

var BASE_MIN PROG_PRIMITIVE = IN_JMP
var BASE_MAX PROG_PRIMITIVE = IN_CATCH_DETAILED + PRIMS_CONNECTS_CNT + PRIMS_DB_CNT + PRIMS_MATH_CNT + PRIMS_MISC_CNT + PRIMS_PROPS_CNT + PRIMS_STACK_CNT + PRIMS_STRINGS_CNT + PRIMS_ARRAY_CNT + PRIMS_FLOAT_CNT + PRIMS_ERROR_CNT + PRIMS_MCP_CNT + PRIMS_REGEX_CNT + PRIMS_INTERNAL_CNT